### PR TITLE
Deprecate send_message

### PR DESCRIPTION
**Pull request by mike-bailey**
A few things happened here, all related to bringing it up to the latest version of slack-ruby-bot.

1. Add celluloid because concurrency errors
2. Add updated Gemfile.lock with latest working version
3. Use client.say for send_fields
4. Edit the send_gif references to be client.say
5. Add spacing according to robocop

_Also please note the "does not respond to sad face" test cases under this fail, I don't know enough about ruby test cases to know what's going on with that_

### CODE REVIEW

**Comment by mike-bailey** [comment]
`Gem::InstallError: nio4r requires Ruby version >= 2.2.2.`
Travis CI build doesn't have latest version of Ruby

**Comment by dblock** [comment]
I'll happily merge once the build is fixed, can help you with the tests.

For Travis, change the ruby version to 2.3.1 or 2.4.0 in https://github.com/slack-ruby/slack-aws/blob/master/.travis.yml.

**Comment by dblock** [comment]
A lot has changed underneath in slack-ruby-bot, if you want to fix that test it should look pretty much like https://github.com/dblock/slack-gamebot/blob/master/spec/slack-gamebot/commands/unknown_spec.rb. That said I think we can just remove it, it's testing that you can send some garbage to the bot and it doesn't respond, something that is already tested in the slack-ruby-bot library.

**Comment by mike-bailey** [comment]
Taken care of. Great project btw! Our company expanded it to EC2 functions, SQS reading and more. It's kind of implementation specific though so I didn't want to open source that stuff.

**Comment by dblock** [comment]
Merged, thank you. Maybe contribute the generic parts from your bot or try to make them more generic?

**Comment by mike-bailey** [comment]
Probably will in the near future.

**Comment by mike-bailey** [comment]
Casual update: Working on this now

**Pull request merged**
